import type { GetServerSidePropsContext, Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { MainCategoryInterface } from "./data";
import { getCategory } from "./components/utils/getCategory";
import type { Viewport } from "next";


export const viewport: Viewport = {
  colorScheme: "normal",
  themeColor: "#4169E1",
  width: "device-width",
  initialScale: 1,
};



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const main_categories: MainCategoryInterface[] | { error: string } = await getCategory();

  return (
    <html lang="en">
      <body className="">
        <header className="flex flex-col items-center">
          {
            (!('error' in main_categories)) && (
              <Header main_categories={main_categories} />
            )
          }
        </header>
        <main className="flex flex-col pt-[65px] w-full min-h-screen">
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );

}



